site_name: Sim2x Documentation
site_author: Tony Hallam
docs_dir: docs
site_dir: site
theme:
  name: material
  language: "en"
  features:
    - navigations.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  palette:
    primary: indigo
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides
use_directory_urls: false
repo_url: https://github.com/trhallam/sim2x
repo_name: trhallam/sim2x

copyright: "Tony Hallam"

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false
  # - pymdownx.snippets:
  #     auto_append: ["docs/hyperlinks.md"]
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - simple:
      # build_docs_dir: docs_build
  - autorefs
  - mkdocs-jupyter:
      execute: true
      kernel_name: python3
      include_source: true
  - mkdocstrings:
      default_handler: python
      watch:
        - src/sim2x
        - scripts
  - include-markdown
  - gen-files:
      scripts:
        - scripts/gen_configs.py


nav:
  - "Home":
    - "About": index.md
    - "Contributing": "contrib.md"
    - "Contact": "contact.md"
    - "Issue Tracker": https://github.com/trhallam/sim2x/issues

  - "User Guide":
    - "Sim2x Framework": "ug/framework.md"
    - "Examples":
      - "Sim2x imp": examples/example_sim2imp.py
      # - "Sim2X rg":
      - "Wavelets": examples/example_wavelets.py
      # - "PSF":
      # - 
      - "Full Sim2seis": examples/example_t1a.py
    - "CLI":
      - "CLI Introduction": "cli/cli_intro.md"
      - "Simulation to Impedance": "cli/imp.md"
      - "Corner Point Grid to Regular Grid": "cli/rg.md"
      - "Impedance to Seismic": "cli/seis.md"

  - "API":
    - "imp": api/imp.md
    - "rg": api/rg.md
    - "Wavelets": api/wavelets.md
    - "seis": api/seis.md
